language: generic
sudo: required

services: docker

before_install:
  # install heroku  cli
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  # build dev image
  - docker build -t app-dev -f Dockerfile.dev .

before_script:
  # run test on dev container
  - docker run -e CI=true app-dev npm run test

script:
  # create prod image
  - docker build -t app-prod .
  # replace image tag with tag corresponding to the repository in registry.heroku.com
  - docker tag app-prod registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    # push to heroku registry
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master
# enviornment variables:
# HEROKU_API_KEY api key for your heroku account can be found in your profile settings
# HEROKU_USERNAME your heroku  username
# HEROKU_APP the name of the heroku  app you created

